esphome:
  name: jc3248w535-dev
  friendly_name: jc3248w535_dev

esp32:
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_FATFS_LFN_STACK: "y"

packages:
  device: !include templates/JC3248W535.yaml

external_components:
  - source:
        type: local
        path: esphome_sd_card/components
    components: [sd_file_server, sd_mmc_card ]

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "cDl2M2IrXylo3iyxktWmDpb7ylL1h/05AX+1Awytf9Y="

ota:
  - platform: esphome
    password: "6fe1e4c9e857f4815fbe3ab682e6d15e"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Jc3248W535-Dev Fallback Hotspot"
    password: !secret web_server_password

captive_portal:


web_server:
  port: 3218
  local: True
  include_internal: true
  auth:
    username: !secret web_server_username
    password: !secret web_server_password
    
    
http_request:

sd_mmc_card:
  id: sdcard1
  mode_1bit: true
  cmd_pin: GPIO11
  clk_pin: GPIO12
  data0_pin: GPIO13
  # power_ctrl_pin: GPIO10
  # data3_pin: GPIO10

  
sd_file_server:
  id: file_server
  url_prefix: file
  root_path: "/"
  sd_mmc_card_id: sdcard1
  enable_deletion: true
  enable_download: true
  enable_upload: true

substitutions:
  displayRotation:          "270"


time:
    - platform: sntp
id: netwotk_time
timezone: Europe/Moscow
servers:
    - 192.168.168.1
    - 0.pool.ntp.org
    - 1.pool.ntp.org
on_time_sync:
    then:
        - logger.log: "On time sync Event."
        - script.execute: cmdUpdateCalendar
    # - script.execute: cmdUpdateDisplay
on_time:
    - seconds: 0
        minutes: '*'
        then:
            - logger.log: "On time sync Event."
