
esp32:
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_FATFS_LFN_STACK: "y"


external_components:
  - source: github://n-serrette/esphome_sd_card
    components: [sd_mmc_card]
  # - source: github://n-serrette/esphome_sd_card
  #   components: [sd_file_server]


sd_mmc_card:
  id: sdcard1
  mode_1bit: true
  cmd_pin: GPIO11
  clk_pin: GPIO12
  data0_pin: GPIO13
  power_ctrl_pin: GPIO10

